specfile_path: fmf.spec
synced_files:
    - fmf.spec

upstream_project_name: fmf
downstream_package_name: fmf

jobs:
- job: copr_build
  trigger: pull_request
  metadata:
    targets:
      - fedora-rawhide-x86_64
      - fedora-30-x86_64
      - fedora-29-x86_64

actions:
  post-upstream-clone:
    - cp docs/header.txt ./man.rst
    - tail -n+7 README.rst >> ./man.rst
    - rst2man $(TMP)/man.rst > $(TMP)/$(PACKAGE)/fmf.1
